/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'index',
    'basic',
    'commandline',
    'project',
    {
      type: 'category',
      label: 'target',
      items: [
        'target/index',
        'target/compile',
        'target/link',
      ],
    },
    {
      type: 'category',
      label: 'dependency',
      items: [
        'dependency/index',
        'dependency/make_dependency',
        'dependency/use_dependency',
        'dependency/boost',
      ],
    },
    {
      type: 'category',
      label: 'subprojects',
      items: [
        'subprojects/index',
        'subprojects/wrap_file',
        'subprojects/wrap_file_examples',
        'subprojects/wrap_db',
      ],
    },
    {
      type: 'category',
      label: 'code generation',
      items: [
        'code_generation/configure_file',
        'code_generation/custom_command',
      ],
    },
    {
      type: 'category',
      label: 'toolchain',
      items: [
        'toolchain/index',
        'toolchain/nativefile',
        'toolchain/crossfile',
        'toolchain/zig_cc',
      ],
    },
    {
      type: 'category',
      label: 'tips',
      items: [
        'tips/c++2b',
        'tips/github-action',
        'tips/cmake',
        'tips/lsp_formatter',
        'tips/using',
      ],
    },
  ],
};

export default sidebars;
